### ISSUE TITLE
Unable to connect x11vnc via rfbproxy

### ISSUE THREAD

**Issue by vipul4work** [replit/rfbproxy#23]
I am unable to connect to the x11vnc server via this rfbproxy on wsl2-ubuntu as well as ubuntu20 docker,
Using the latest release of this rfbproxy and x11vnc,  x11vnc server is running on port 5901 and rfbproxy on port 5900 and i am trying to connect via vnc viewer and getting this loader 

Can you please take a look at this or tell me if i am using it wrong

rfbproxy command 
`RUST_LOG=debug rfbproxy --http-server --rfb-server=0.0.0.0:5901
`

x11vnc command
`x11vnc -display :1 -xkb -forever -shared -repeat -capslock -rfbport  5901`

<img width="377" alt="image" src="https://user-images.githubusercontent.com/104551049/171140864-f242fe8e-c82d-4b54-a947-73bd1f63a4a9.png">

**Comment by lhchavez** [comment]
This project won't work with VNC viewer because it only supports RFB-over-WebSockets (and not RFB-over-TCP). Which means that the only client that will work is https://novnc.com/

let me add that to the readme.
